# Fig 1B: Q1 holdout validation (per-species recall + BA comparison)
# Requires: results/fig1b_holdout_for_r.json (generated by export_fig_data_for_r.py)
# Output: results/figures/rf/fig1b_holdout_validation.{png,pdf}

library(ggplot2)
library(dplyr)
library(jsonlite)
library(patchwork)

source("src/visualization/eskape_theme.R")

d <- fromJSON("results/fig1b_holdout_for_r.json")

SP_ORDER  <- c("AB", "EC", "EF", "KP", "PA", "SA")
SP_KEYS   <- c("abaumannii", "ecloaceae", "efaecium", "kpneumoniae", "paeruginosa", "saureus")

recall_df <- data.frame(
  species = factor(SP_ORDER, levels = rev(SP_ORDER)),
  recall  = unlist(d$recalls[SP_KEYS]),
  color   = SP_COLORS[SP_ORDER]
)

p_recall <- ggplot(recall_df, aes(x = recall, y = species, fill = species)) +
  geom_col(width = 0.6, show.legend = FALSE) +
  geom_text(aes(label = sprintf("%.3f", recall),
                x = pmax(recall - 0.01, 0.01)),
            hjust = 1, color = "white", size = 2.8, fontface = "bold") +
  geom_vline(xintercept = 1.0, linetype = "dashed", color = "grey50", linewidth = 0.4) +
  scale_fill_manual(values = SP_COLORS) +
  scale_x_continuous(limits = c(0, 1.05), expand = c(0, 0),
                     breaks = c(0, 0.25, 0.5, 0.75, 1.0)) +
  scale_y_discrete(labels = SP_LABELS[rev(SP_ORDER)]) +
  labs(x = "Recall (holdout)", y = NULL, tag = "B") +
  theme_eskape(base_size = 9) +
  theme(panel.grid.major.y = element_blank(),
        axis.text.y = element_text(face = "italic"))

ba_df <- data.frame(
  estimate = c("Cross-validation", "Holdout"),
  ba       = c(d$cv_ba, d$holdout_ba),
  lo       = c(d$cv_ci[[1]], d$holdout_ci[[1]]),
  hi       = c(d$cv_ci[[2]], d$holdout_ci[[2]])
) %>%
  mutate(estimate = factor(estimate, levels = c("Holdout", "Cross-validation")))

p_ba <- ggplot(ba_df, aes(x = ba, y = estimate)) +
  geom_vline(xintercept = 0.167, linetype = "dotted", color = "grey60", linewidth = 0.5) +
  geom_errorbar(aes(xmin = lo, xmax = hi), width = 0.15, linewidth = 0.8, color = "#0072B2") +
  geom_point(size = 3.5, color = "#0072B2", fill = "white", shape = 21, stroke = 1.5) +
  geom_text(aes(label = sprintf("%.3f\n[%.3f–%.3f]", ba, lo, hi)),
            nudge_y = 0.25, size = 2.5, lineheight = 0.9) +
  scale_x_continuous(limits = c(0.8, 1.02), breaks = seq(0.80, 1.00, 0.05)) +
  labs(x = "Balanced accuracy", y = NULL, tag = "C") +
  theme_eskape(base_size = 9) +
  theme(panel.grid.major.y = element_blank())

fig <- p_recall + p_ba +
  plot_layout(widths = c(1.6, 1)) +
  plot_annotation(theme = theme(plot.margin = margin(4, 4, 4, 4)))

dir.create("results/figures/rf", recursive = TRUE, showWarnings = FALSE)
save_fig(fig, "results/figures/rf/fig1b_holdout_validation", width = 8, height = 3.5)
