# Fig 4B: SHAP per-species heatmap (top 20 features, mean SHAP when present)
# Requires: results/fig4b_heatmap_for_r.csv (generated by export_fig_data_for_r.py)
# Output: results/figures/interpretation/fig4b_shap_heatmap.{png,pdf}

library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)

source("src/visualization/eskape_theme.R")

raw <- read_csv("results/fig4b_heatmap_for_r.csv", show_col_types = FALSE)

SP_ORDER  <- c("AB", "EC", "EF", "KP", "PA", "SA")
SP_FULL   <- c("A. baumannii", "E. cloacae", "E. faecium",
               "K. pneumoniae", "P. aeruginosa", "S. aureus")

# Feature labels ordered rank 1 (top) to rank 20 (bottom)
feat_levels <- rev(raw$label)  # rev so rank 1 appears at top of y-axis

df_long <- raw %>%
  pivot_longer(cols = all_of(SP_ORDER), names_to = "species", values_to = "shap") %>%
  mutate(
    species = factor(species, levels = SP_ORDER,
                     labels = paste0("italic('", SP_FULL, "')")),
    feature = factor(label, levels = feat_levels),
    named   = (category == "named")
  )

shap_max <- max(abs(df_long$shap), na.rm = TRUE)
clim     <- ceiling(shap_max * 100) / 100  # round up to nearest 0.01

p <- ggplot(df_long, aes(x = species, y = feature, fill = shap)) +
  geom_tile(color = "white", linewidth = 0.4) +
  geom_text(aes(label = sprintf("%.3f", shap),
                color  = abs(shap) > clim * 0.55),
            size = 2.3) +
  scale_fill_gradient2(
    low      = "#0072B2",
    mid      = "white",
    high     = "#D55E00",
    midpoint = 0,
    limits   = c(-clim, clim),
    name     = "Mean SHAP\n(present genomes)"
  ) +
  scale_color_manual(values = c("TRUE" = "white", "FALSE" = "grey25"), guide = "none") +
  scale_x_discrete(labels = function(x) parse(text = x),
                   position = "top") +
  labs(x = NULL, y = NULL, tag = "B") +
  theme_eskape(base_size = 8.5) +
  theme(
    axis.text.x        = element_text(angle = 40, hjust = 0, face = "italic", size = 7.5),
    axis.text.y        = element_text(size = 7.5),
    panel.grid         = element_blank(),
    panel.border       = element_blank(),
    legend.position    = "right",
    legend.key.height  = unit(1.2, "cm"),
    plot.margin        = margin(t = 30, r = 5, b = 5, l = 5)
  )

dir.create("results/figures/interpretation", recursive = TRUE, showWarnings = FALSE)
save_fig(p, "results/figures/interpretation/fig4b_shap_heatmap", width = 6.5, height = 7)
