# Fig 4A: Global SHAP beeswarm (top 20 features, Q1 RF, all species)
# Requires: results/fig4a_beeswarm_for_r.csv (generated by export_fig_data_for_r.py)
# Output: results/figures/interpretation/fig4a_shap_global_beeswarm.{png,pdf}

library(ggplot2)
library(ggbeeswarm)
library(readr)
library(dplyr)

source("src/visualization/eskape_theme.R")

df <- read_csv("results/fig4a_beeswarm_for_r.csv", show_col_types = FALSE)

# Order features rank 1 (top) to rank 20 (bottom) on y-axis
feat_levels <- df %>%
  distinct(feature, rank) %>%
  arrange(desc(rank)) %>%
  pull(feature)

df <- df %>%
  mutate(feature = factor(feature, levels = feat_levels))

# SHAP colour palette: blue (absent, 0) → red (present, 1), matching Python SHAP
shap_pal <- colorRampPalette(c("#1E88E5", "#7B1FA2", "#E53935"))(256)

p <- ggplot(df, aes(x = shap_value, y = feature, colour = feature_value)) +
  geom_quasirandom(
    groupOnX = FALSE,
    size     = 0.35,
    alpha    = 0.55,
    bandwidth = 0.4,
    varwidth  = FALSE
  ) +
  geom_vline(xintercept = 0, colour = "grey40", linewidth = 0.4) +
  scale_colour_gradientn(
    colours  = shap_pal,
    limits   = c(0, 1),
    breaks   = c(0, 1),
    labels   = c("Low", "High"),
    name     = "Feature\nvalue",
    guide    = guide_colorbar(
      barwidth  = unit(0.35, "cm"),
      barheight = unit(3.0,  "cm"),
      ticks     = FALSE,
      title.position = "top"
    )
  ) +
  scale_x_continuous(
    name   = "SHAP value (impact on model output)",
    breaks = seq(0, 0.15, by = 0.025),
    limits = c(0, 0.155),
    expand = expansion(mult = c(0.01, 0.01))
  ) +
  labs(
    tag = "A",
    y   = "Defence system"
  ) +
  theme_eskape(base_size = 8.5) +
  theme(
    plot.tag         = element_text(size = 9, face = "bold"),
    axis.text.y      = element_text(size = 7.5),
    axis.text.x      = element_text(size = 7.5),
    axis.title       = element_text(size = 8.5),
    legend.position  = "right",
    legend.title     = element_text(size = 7.5),
    legend.text      = element_text(size = 7),
    plot.margin      = margin(t = 10, r = 10, b = 5, l = 5)
  )

dir.create("results/figures/interpretation", recursive = TRUE, showWarnings = FALSE)
save_fig(p, "results/figures/interpretation/fig4a_shap_global_beeswarm", width = 6.5, height = 7)
