# =============================================================================
# Figure 2: Q2 ARG burden classification
# Panels: A — per-species AUROC forest plot | B — within-phylogroup driver dotplot
# Each panel is generated by its own script at its optimal width, then stacked
# vertically here using grid (R-native replacement for combine_panels.py).
#
# Run from project root: Rscript src/visualization/figure2.R
# Output: results/figures/final/figure2.{png,pdf}
# =============================================================================

library(grid)
library(png)

source("src/visualization/eskape_theme.R")

# =============================================================================
# Section 1: Generate individual panels
# =============================================================================

source("src/visualization/fig3a_q2_auroc_forest.R")   # → results/figures/q2/fig2a_q2_auroc_forest.png
source("src/visualization/fig3b_q2_driver_dotplot.R")  # → results/figures/q2/fig2b_q2_driver_dotplot.png

# =============================================================================
# Section 2: Stack panels vertically (centre narrower panel on white canvas)
# =============================================================================

img_a <- readPNG("results/figures/q2/fig2a_q2_auroc_forest.png")
img_b <- readPNG("results/figures/q2/fig2b_q2_driver_dotplot.png")

h_a <- nrow(img_a); w_a <- ncol(img_a)
h_b <- nrow(img_b); w_b <- ncol(img_b)

DPI <- 300
GAP <- 30   # px gap between panels, matching combine_panels.py

canvas_w <- max(w_a, w_b)
canvas_h <- h_a + GAP + h_b

out_w_in <- canvas_w / DPI
out_h_in <- canvas_h / DPI

out_png <- "results/figures/final/figure2.png"
out_pdf <- "results/figures/final/figure2.pdf"

# -- PNG (ragg for clean rendering) --
ragg::agg_png(out_png, width = canvas_w, height = canvas_h, units = "px",
              res = DPI, background = "white")

grid.newpage()

# grid.raster x/y anchor is the centre of the image in npc coords
y_a <- (canvas_h - h_a / 2) / canvas_h   # centre of Panel A from bottom
y_b <- (h_b / 2) / canvas_h              # centre of Panel B from bottom

grid.raster(img_a, x = 0.5, y = y_a,
            width  = unit(w_a / canvas_w, "npc"),
            height = unit(h_a / canvas_h, "npc"),
            interpolate = TRUE)
grid.raster(img_b, x = 0.5, y = y_b,
            width  = unit(w_b / canvas_w, "npc"),
            height = unit(h_b / canvas_h, "npc"),
            interpolate = TRUE)

dev.off()

# -- PDF (embed as raster page) --
pdf(out_pdf, width = out_w_in, height = out_h_in)
grid.newpage()
grid.raster(img_a, x = 0.5, y = y_a,
            width  = unit(w_a / canvas_w, "npc"),
            height = unit(h_a / canvas_h, "npc"),
            interpolate = TRUE)
grid.raster(img_b, x = 0.5, y = y_b,
            width  = unit(w_b / canvas_w, "npc"),
            height = unit(h_b / canvas_h, "npc"),
            interpolate = TRUE)
dev.off()

message("Saved: results/figures/final/figure2.png/.pdf")
